### ISSUE TITLE
即時資訊頁面

### ISSUE THREAD

**Issue by e22346845** [karateboy/YL#5]
依驗收規定， 即時空氣品質資訊 的頁面 還需增加 各測站的分類(如：一般、工業測站等)，再麻煩了

**Comment by karateboy** [comment]
請問你說的是首頁嗎?

**Comment by e22346845** [comment]
是的，增加之位置如下圖所示，再麻煩囉，謝謝！

![4](https://cloud.githubusercontent.com/assets/25893727/23285224/cf196a28-fa6a-11e6-88f8-5ad0d20bc5a2.JPG)

**Comment by karateboy** [comment]
已修正

**Comment by e22346845** [comment]
OK~辛苦了，謝謝！
