### ISSUE TITLE
測站資訊頁面需每一測項皆有單位

### ISSUE THREAD

**Issue by e22346845** [karateboy/YL#6]

**Comment by karateboy** [comment]
不太了解這個問題...可以用張圖說明一下嗎?

**Comment by e22346845** [comment]
在查詢的地方，都有顯示測項之單位，如下圖螢光筆所示：
![2](https://cloud.githubusercontent.com/assets/25893727/23285008/90f0e7d6-fa69-11e6-98a0-c9485373cff1.JPG)


而在篩選排序(PM2.5超標篩選、測項超標篩選、行政轄區測項排序、測站測項排序)那邊，也希望每項測項都有單位，如下圖螢光筆所示，希望於同樣地方，呈現單位即可，謝謝！
![1](https://cloud.githubusercontent.com/assets/25893727/23285024/b6dc0df4-fa69-11e6-8c2e-f9d95f36ef02.JPG)

如有不清楚之地方，會再詳細說明，感謝！

**Comment by karateboy** [comment]
修好了...請驗證

**Comment by e22346845** [comment]
OK~已確定~3QQ!
