### ISSUE TITLE
3/14驗收前需確認之功能(急)

### ISSUE THREAD

**Issue by e22346845** [karateboy/YL#7]
依合約書規範，以下之功能需要做確認
1.須能替除無效值及數據異常等資料。
2.提供於圖表上選擇是否標示出各測項EPA公告日均標準值或年均標準值之功能。(如下列網址之資訊作呈現，http://taqm.epa.gov.tw/taqm/tw/b0206.aspx)

希望第一點的功能，能有個確切驗收的方式，再麻煩了，感謝！

**Comment by karateboy** [comment]
1. 無效值不會出現在歷史趨勢圖的查詢, 例如查詢汐止2/20 - 2/21的歷史趨勢圖. 無效數值就會不會出現在圖上
![image](https://cloud.githubusercontent.com/assets/1067042/23604072/8cbf1472-0292-11e7-8c0d-52b47274d98c.png)

**Comment by karateboy** [comment]
2. 連結是法規值吧...?

**Comment by e22346845** [comment]
對~只是告知這些測項 在趨勢圖的地方，要顯示法規值，謝謝！

**Comment by e22346845** [comment]
感謝 提出 無效值的呈現方式，謝謝！

**Comment by karateboy** [comment]
現在小時平均值已經會自動顯示 (如果監測值有接近)

**Comment by e22346845** [comment]
ok，先這樣子就好！
