### ISSUE TITLE
無法連上這個網站

### ISSUE THREAD

**Issue by e22346845** [karateboy/YL#8]
106/04/12 17:09 使用空氣品質資訊系統  http://59.124.12.69:9000/ 
無法連上這個網站

![default](https://cloud.githubusercontent.com/assets/25893727/24950187/bcc55e60-1fa2-11e7-90fc-50418c609758.JPG)

**Comment by karateboy** [comment]
應該是公司網路斷線...現在已經恢復

**Comment by e22346845** [comment]
106/04/17 15：23
![default](https://cloud.githubusercontent.com/assets/25893727/25082254/28c83136-2382-11e7-8e36-98a5446b05a4.JPG)

**Comment by karateboy** [comment]
主機重開...已經修好
